### ISSUE TITLE
Add 'Letzte Änderung' notification to footer

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/zoonotify-client#16]
see https://mibi-portal.bfr.bund.de/

**Comment by GerberI** [comment]
The last change written to the package.json by jenkins is not read to the environment variable during the build process. This is a feature working in angular but not in React. As a result "invalid date" is displayed instead of the actual building date.

Possible solutions:
- Check if their is a react solution to set environment variables during build process
- Use the node config.json mechanism to save the build date during building and deploy the config to server, so the client can read form config.json during runtime
- Deploy the package.json to server so the client can read the date during runtime
