### ISSUE TITLE
As a user I would like to be able to copy the title of the figures in the evaluation section (low prio)

### ISSUE THREAD

**Issue by tasjacrease** [SiLeBAT/zoonotify-client#791]
I can copy the text for the description of the figure, but I am unable to copy the text of the title.

**Comment by mahtabiltarabian** [comment]
If clicking on the titles triggers an action (like opening a box with details), then the text is likely not selectable because it's functioning as a button or link, not as static text. In such cases, the text is often part of an interactive element designed for user interaction rather than text selection.,,, for this i implemet icon for copy title to clipboard
<img width="1066" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk1XQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5789c52e37b3e4d93723ca4e871804c6553702d/image.png" alt="image.png" />

**Comment by mahtabiltarabian** [comment]
yes of course
